[build]
    functions = "src/functions"
    command = "node src/server.js"
    publish =  "src/public"

[dev]
    publish = "src/public"
    port = 8000

[[redirects]]
    to = "/.netlify/functions/api/:splat"
    from = "/*"
    status = 200
